const data = {
  products: [
    {
      "id": 1001,
      "category": "Category 4",
      "name": "Product 1",
      "image": "https://picsum.photos/400?image=524",
      "stock": false,
      "price": "2260.955",
      "description": " Integer suscipit sapien magna, vitae hendrerit eros luctus ut. Quisque id suscipit augue, rutrum faucibus tortor. Proin ac tortor orci. Nullam erat justo, bibendum at ultricies sed, mollis ut nunc. Nunc leo nunc, placerat ac elementum vel, luctus eget lacus. Nunc ultrices pulvinar nulla, eu viverra ligula aliquet vel. In ullamcorper risus risus, non efficitur nunc eleifend vitae. Nulla rutrum placerat nibh a laoreet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque in felis in risus ultricies tempor. Maecenas sit amet ornare diam. Praesent fermentum odio non aliquet euismod. Quisque commodo et lectus nec maximus. ",
      "slug": "product-1",
      "brand": "armaani",
      "rating": 4
    },
    {
      "id": 1002,
      "category": "Category 2",
      "name": "Product 2",
      "image": "https://picsum.photos/400?image=48",
      "stock": false,
      "price": "2315.658",
      "description": " Integer suscipit sapien magna, vitae hendrerit eros luctus ut. Quisque id suscipit augue, rutrum faucibus tortor. Proin ac tortor orci. Nullam erat justo, bibendum at ultricies sed, mollis ut nunc. Nunc leo nunc, placerat ac elementum vel, luctus eget lacus. Nunc ultrices pulvinar nulla, eu viverra ligula aliquet vel. In ullamcorper risus risus, non efficitur nunc eleifend vitae. Nulla rutrum placerat nibh a laoreet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque in felis in risus ultricies tempor. Maecenas sit amet ornare diam. Praesent fermentum odio non aliquet euismod. Quisque commodo et lectus nec maximus. ",
      "slug": "product-2",
      "brand": "armaani",
      "rating": 4
    },
    {
      "id": 1003,
      "category": "Category 4",
      "name": "Product 3",
      "image": "https://picsum.photos/400?image=376",
      "stock": false,
      "price": "3147.706",
      "description": " Integer suscipit sapien magna, vitae hendrerit eros luctus ut. Quisque id suscipit augue, rutrum faucibus tortor. Proin ac tortor orci. Nullam erat justo, bibendum at ultricies sed, mollis ut nunc. Nunc leo nunc, placerat ac elementum vel, luctus eget lacus. Nunc ultrices pulvinar nulla, eu viverra ligula aliquet vel. In ullamcorper risus risus, non efficitur nunc eleifend vitae. Nulla rutrum placerat nibh a laoreet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque in felis in risus ultricies tempor. Maecenas sit amet ornare diam. Praesent fermentum odio non aliquet euismod. Quisque commodo et lectus nec maximus. ",
      "slug": "product-3",
      "brand": "armaani",
      "rating": 3
    },
    {
      "id": 1004,
      "category": "Category 2",
      "name": "Product 4",
      "image": "https://picsum.photos/400?image=739",
      "stock": false,
      "price": "3569.424",
      "description": " Integer suscipit sapien magna, vitae hendrerit eros luctus ut. Quisque id suscipit augue, rutrum faucibus tortor. Proin ac tortor orci. Nullam erat justo, bibendum at ultricies sed, mollis ut nunc. Nunc leo nunc, placerat ac elementum vel, luctus eget lacus. Nunc ultrices pulvinar nulla, eu viverra ligula aliquet vel. In ullamcorper risus risus, non efficitur nunc eleifend vitae. Nulla rutrum placerat nibh a laoreet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque in felis in risus ultricies tempor. Maecenas sit amet ornare diam. Praesent fermentum odio non aliquet euismod. Quisque commodo et lectus nec maximus. ",
      "slug": "product-4",
      "brand": "armaani",
      "rating": 3
    },
    {
      "id": 1005,
      "category": "Category 1",
      "name": "Product 5",
      "image": "https://picsum.photos/400?image=216",
      "stock": false,
      "price": "3767.674",
      "description": " Integer suscipit sapien magna, vitae hendrerit eros luctus ut. Quisque id suscipit augue, rutrum faucibus tortor. Proin ac tortor orci. Nullam erat justo, bibendum at ultricies sed, mollis ut nunc. Nunc leo nunc, placerat ac elementum vel, luctus eget lacus. Nunc ultrices pulvinar nulla, eu viverra ligula aliquet vel. In ullamcorper risus risus, non efficitur nunc eleifend vitae. Nulla rutrum placerat nibh a laoreet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque in felis in risus ultricies tempor. Maecenas sit amet ornare diam. Praesent fermentum odio non aliquet euismod. Quisque commodo et lectus nec maximus. ",
      "slug": "product-5",
      "brand": "armaani",
      "rating": 4
    },
    {
      "id": 1006,
      "category": "Category 3",
      "name": "Product 6",
      "image": "https://picsum.photos/400?image=808",
      "stock": true,
      "price": "2827.467",
      "description": " Integer suscipit sapien magna, vitae hendrerit eros luctus ut. Quisque id suscipit augue, rutrum faucibus tortor. Proin ac tortor orci. Nullam erat justo, bibendum at ultricies sed, mollis ut nunc. Nunc leo nunc, placerat ac elementum vel, luctus eget lacus. Nunc ultrices pulvinar nulla, eu viverra ligula aliquet vel. In ullamcorper risus risus, non efficitur nunc eleifend vitae. Nulla rutrum placerat nibh a laoreet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque in felis in risus ultricies tempor. Maecenas sit amet ornare diam. Praesent fermentum odio non aliquet euismod. Quisque commodo et lectus nec maximus. ",
      "slug": "product-6",
      "brand": "armaani",
      "rating": 4
    },
    {
      "id": 1007,
      "category": "Category 3",
      "name": "Product 7",
      "image": "https://picsum.photos/400?image=760",
      "stock": true,
      "price": "2115.582",
      "description": " Integer suscipit sapien magna, vitae hendrerit eros luctus ut. Quisque id suscipit augue, rutrum faucibus tortor. Proin ac tortor orci. Nullam erat justo, bibendum at ultricies sed, mollis ut nunc. Nunc leo nunc, placerat ac elementum vel, luctus eget lacus. Nunc ultrices pulvinar nulla, eu viverra ligula aliquet vel. In ullamcorper risus risus, non efficitur nunc eleifend vitae. Nulla rutrum placerat nibh a laoreet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque in felis in risus ultricies tempor. Maecenas sit amet ornare diam. Praesent fermentum odio non aliquet euismod. Quisque commodo et lectus nec maximus. ",
      "slug": "product-7",
      "brand": "armaani",
      "rating": 3
    },
    {
      "id": 1008,
      "category": "Category 1",
      "name": "Product 8",
      "image": "https://picsum.photos/400?image=156",
      "stock": false,
      "price": "3685.030",
      "description": " Integer suscipit sapien magna, vitae hendrerit eros luctus ut. Quisque id suscipit augue, rutrum faucibus tortor. Proin ac tortor orci. Nullam erat justo, bibendum at ultricies sed, mollis ut nunc. Nunc leo nunc, placerat ac elementum vel, luctus eget lacus. Nunc ultrices pulvinar nulla, eu viverra ligula aliquet vel. In ullamcorper risus risus, non efficitur nunc eleifend vitae. Nulla rutrum placerat nibh a laoreet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque in felis in risus ultricies tempor. Maecenas sit amet ornare diam. Praesent fermentum odio non aliquet euismod. Quisque commodo et lectus nec maximus. ",
      "slug": "product-8",
      "brand": "armaani",
      "rating": 4
    },
    {
      "id": 1009,
      "category": "Category 4",
      "name": "Product 9",
      "image": "https://picsum.photos/400?image=581",
      "stock": false,
      "price": "3524.829",
      "description": " Integer suscipit sapien magna, vitae hendrerit eros luctus ut. Quisque id suscipit augue, rutrum faucibus tortor. Proin ac tortor orci. Nullam erat justo, bibendum at ultricies sed, mollis ut nunc. Nunc leo nunc, placerat ac elementum vel, luctus eget lacus. Nunc ultrices pulvinar nulla, eu viverra ligula aliquet vel. In ullamcorper risus risus, non efficitur nunc eleifend vitae. Nulla rutrum placerat nibh a laoreet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque in felis in risus ultricies tempor. Maecenas sit amet ornare diam. Praesent fermentum odio non aliquet euismod. Quisque commodo et lectus nec maximus. ",
      "slug": "product-9",
      "brand": "armaani",
      "rating": 3
    },
    {
      "id": 1010,
      "category": "Category 3",
      "name": "Product 10",
      "image": "https://picsum.photos/400?image=884",
      "stock": false,
      "price": "3737.914",
      "description": " Integer suscipit sapien magna, vitae hendrerit eros luctus ut. Quisque id suscipit augue, rutrum faucibus tortor. Proin ac tortor orci. Nullam erat justo, bibendum at ultricies sed, mollis ut nunc. Nunc leo nunc, placerat ac elementum vel, luctus eget lacus. Nunc ultrices pulvinar nulla, eu viverra ligula aliquet vel. In ullamcorper risus risus, non efficitur nunc eleifend vitae. Nulla rutrum placerat nibh a laoreet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque in felis in risus ultricies tempor. Maecenas sit amet ornare diam. Praesent fermentum odio non aliquet euismod. Quisque commodo et lectus nec maximus. ",
      "slug": "product-10",
      "brand": "armaani",
      "rating": 4
    },
    {
      "id": 1011,
      "category": "Category 2",
      "name": "Product 11",
      "image": "https://picsum.photos/400?image=276",
      "stock": true,
      "price": "3692.578",
      "description": " Integer suscipit sapien magna, vitae hendrerit eros luctus ut. Quisque id suscipit augue, rutrum faucibus tortor. Proin ac tortor orci. Nullam erat justo, bibendum at ultricies sed, mollis ut nunc. Nunc leo nunc, placerat ac elementum vel, luctus eget lacus. Nunc ultrices pulvinar nulla, eu viverra ligula aliquet vel. In ullamcorper risus risus, non efficitur nunc eleifend vitae. Nulla rutrum placerat nibh a laoreet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque in felis in risus ultricies tempor. Maecenas sit amet ornare diam. Praesent fermentum odio non aliquet euismod. Quisque commodo et lectus nec maximus. ",
      "slug": "product-11",
      "brand": "armaani",
      "rating": 4
    },
    {
      "id": 1012,
      "category": "Category 1",
      "name": "Product 12",
      "image": "https://picsum.photos/400?image=656",
      "stock": false,
      "price": "2320.489",
      "description": " Integer suscipit sapien magna, vitae hendrerit eros luctus ut. Quisque id suscipit augue, rutrum faucibus tortor. Proin ac tortor orci. Nullam erat justo, bibendum at ultricies sed, mollis ut nunc. Nunc leo nunc, placerat ac elementum vel, luctus eget lacus. Nunc ultrices pulvinar nulla, eu viverra ligula aliquet vel. In ullamcorper risus risus, non efficitur nunc eleifend vitae. Nulla rutrum placerat nibh a laoreet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque in felis in risus ultricies tempor. Maecenas sit amet ornare diam. Praesent fermentum odio non aliquet euismod. Quisque commodo et lectus nec maximus. ",
      "slug": "product-12",
      "brand": "armaani",
      "rating": 3
    },
    {
      "id": 1013,
      "category": "Category 2",
      "name": "Product 13",
      "image": "https://picsum.photos/400?image=962",
      "stock": false,
      "price": "3659.186",
      "description": " Integer suscipit sapien magna, vitae hendrerit eros luctus ut. Quisque id suscipit augue, rutrum faucibus tortor. Proin ac tortor orci. Nullam erat justo, bibendum at ultricies sed, mollis ut nunc. Nunc leo nunc, placerat ac elementum vel, luctus eget lacus. Nunc ultrices pulvinar nulla, eu viverra ligula aliquet vel. In ullamcorper risus risus, non efficitur nunc eleifend vitae. Nulla rutrum placerat nibh a laoreet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque in felis in risus ultricies tempor. Maecenas sit amet ornare diam. Praesent fermentum odio non aliquet euismod. Quisque commodo et lectus nec maximus. ",
      "slug": "product-13",
      "brand": "armaani",
      "rating": 4
    },
    {
      "id": 1014,
      "category": "Category 4",
      "name": "Product 14",
      "image": "https://picsum.photos/400?image=575",
      "stock": false,
      "price": "3510.336",
      "description": " Integer suscipit sapien magna, vitae hendrerit eros luctus ut. Quisque id suscipit augue, rutrum faucibus tortor. Proin ac tortor orci. Nullam erat justo, bibendum at ultricies sed, mollis ut nunc. Nunc leo nunc, placerat ac elementum vel, luctus eget lacus. Nunc ultrices pulvinar nulla, eu viverra ligula aliquet vel. In ullamcorper risus risus, non efficitur nunc eleifend vitae. Nulla rutrum placerat nibh a laoreet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque in felis in risus ultricies tempor. Maecenas sit amet ornare diam. Praesent fermentum odio non aliquet euismod. Quisque commodo et lectus nec maximus. ",
      "slug": "product-14",
      "brand": "armaani",
      "rating": 4
    },
    {
      "id": 1015,
      "category": "Category 4",
      "name": "Product 15",
      "image": "https://picsum.photos/400?image=820",
      "stock": true,
      "price": "3369.397",
      "description": " Integer suscipit sapien magna, vitae hendrerit eros luctus ut. Quisque id suscipit augue, rutrum faucibus tortor. Proin ac tortor orci. Nullam erat justo, bibendum at ultricies sed, mollis ut nunc. Nunc leo nunc, placerat ac elementum vel, luctus eget lacus. Nunc ultrices pulvinar nulla, eu viverra ligula aliquet vel. In ullamcorper risus risus, non efficitur nunc eleifend vitae. Nulla rutrum placerat nibh a laoreet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque in felis in risus ultricies tempor. Maecenas sit amet ornare diam. Praesent fermentum odio non aliquet euismod. Quisque commodo et lectus nec maximus. ",
      "slug": "product-15",
      "brand": "armaani",
      "rating": 4
    },
    {
      "id": 1016,
      "category": "Category 3",
      "name": "Product 16",
      "image": "https://picsum.photos/400?image=370",
      "stock": true,
      "price": "2407.228",
      "description": " Integer suscipit sapien magna, vitae hendrerit eros luctus ut. Quisque id suscipit augue, rutrum faucibus tortor. Proin ac tortor orci. Nullam erat justo, bibendum at ultricies sed, mollis ut nunc. Nunc leo nunc, placerat ac elementum vel, luctus eget lacus. Nunc ultrices pulvinar nulla, eu viverra ligula aliquet vel. In ullamcorper risus risus, non efficitur nunc eleifend vitae. Nulla rutrum placerat nibh a laoreet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque in felis in risus ultricies tempor. Maecenas sit amet ornare diam. Praesent fermentum odio non aliquet euismod. Quisque commodo et lectus nec maximus. ",
      "slug": "product-16",
      "brand": "armaani",
      "rating": 4
    },
    {
      "id": 1017,
      "category": "Category 3",
      "name": "Product 17",
      "image": "https://picsum.photos/400?image=311",
      "stock": true,
      "price": "2060.037",
      "description": " Integer suscipit sapien magna, vitae hendrerit eros luctus ut. Quisque id suscipit augue, rutrum faucibus tortor. Proin ac tortor orci. Nullam erat justo, bibendum at ultricies sed, mollis ut nunc. Nunc leo nunc, placerat ac elementum vel, luctus eget lacus. Nunc ultrices pulvinar nulla, eu viverra ligula aliquet vel. In ullamcorper risus risus, non efficitur nunc eleifend vitae. Nulla rutrum placerat nibh a laoreet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque in felis in risus ultricies tempor. Maecenas sit amet ornare diam. Praesent fermentum odio non aliquet euismod. Quisque commodo et lectus nec maximus. ",
      "slug": "product-17",
      "brand": "armaani",
      "rating": 4
    },
    {
      "id": 1018,
      "category": "Category 3",
      "name": "Product 18",
      "image": "https://picsum.photos/400?image=930",
      "stock": true,
      "price": "2511.776",
      "description": " Integer suscipit sapien magna, vitae hendrerit eros luctus ut. Quisque id suscipit augue, rutrum faucibus tortor. Proin ac tortor orci. Nullam erat justo, bibendum at ultricies sed, mollis ut nunc. Nunc leo nunc, placerat ac elementum vel, luctus eget lacus. Nunc ultrices pulvinar nulla, eu viverra ligula aliquet vel. In ullamcorper risus risus, non efficitur nunc eleifend vitae. Nulla rutrum placerat nibh a laoreet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque in felis in risus ultricies tempor. Maecenas sit amet ornare diam. Praesent fermentum odio non aliquet euismod. Quisque commodo et lectus nec maximus. ",
      "slug": "product-18",
      "brand": "armaani",
      "rating": 3
    },
    {
      "id": 1019,
      "category": "Category 4",
      "name": "Product 19",
      "image": "https://picsum.photos/400?image=578",
      "stock": true,
      "price": "1660.724",
      "description": " Integer suscipit sapien magna, vitae hendrerit eros luctus ut. Quisque id suscipit augue, rutrum faucibus tortor. Proin ac tortor orci. Nullam erat justo, bibendum at ultricies sed, mollis ut nunc. Nunc leo nunc, placerat ac elementum vel, luctus eget lacus. Nunc ultrices pulvinar nulla, eu viverra ligula aliquet vel. In ullamcorper risus risus, non efficitur nunc eleifend vitae. Nulla rutrum placerat nibh a laoreet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque in felis in risus ultricies tempor. Maecenas sit amet ornare diam. Praesent fermentum odio non aliquet euismod. Quisque commodo et lectus nec maximus. ",
      "slug": "product-19",
      "brand": "armaani",
      "rating": 4
    },
    {
      "id": 1020,
      "category": "Category 3",
      "name": "Product 20",
      "image": "https://picsum.photos/400?image=970",
      "stock": true,
      "price": "1184.583",
      "description": " Integer suscipit sapien magna, vitae hendrerit eros luctus ut. Quisque id suscipit augue, rutrum faucibus tortor. Proin ac tortor orci. Nullam erat justo, bibendum at ultricies sed, mollis ut nunc. Nunc leo nunc, placerat ac elementum vel, luctus eget lacus. Nunc ultrices pulvinar nulla, eu viverra ligula aliquet vel. In ullamcorper risus risus, non efficitur nunc eleifend vitae. Nulla rutrum placerat nibh a laoreet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque in felis in risus ultricies tempor. Maecenas sit amet ornare diam. Praesent fermentum odio non aliquet euismod. Quisque commodo et lectus nec maximus. ",
      "slug": "product-20",
      "brand": "armaani",
      "rating": 4
    },
    {
      "id": 1021,
      "category": "Category 3",
      "name": "Product 21",
      "image": "https://picsum.photos/400?image=635",
      "stock": false,
      "price": "3478.057",
      "description": " Integer suscipit sapien magna, vitae hendrerit eros luctus ut. Quisque id suscipit augue, rutrum faucibus tortor. Proin ac tortor orci. Nullam erat justo, bibendum at ultricies sed, mollis ut nunc. Nunc leo nunc, placerat ac elementum vel, luctus eget lacus. Nunc ultrices pulvinar nulla, eu viverra ligula aliquet vel. In ullamcorper risus risus, non efficitur nunc eleifend vitae. Nulla rutrum placerat nibh a laoreet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque in felis in risus ultricies tempor. Maecenas sit amet ornare diam. Praesent fermentum odio non aliquet euismod. Quisque commodo et lectus nec maximus. ",
      "slug": "product-21",
      "brand": "armaani",
      "rating": 3
    },
    {
      "id": 1022,
      "category": "Category 2",
      "name": "Product 22",
      "image": "https://picsum.photos/400?image=522",
      "stock": false,
      "price": "2349.004",
      "description": " Integer suscipit sapien magna, vitae hendrerit eros luctus ut. Quisque id suscipit augue, rutrum faucibus tortor. Proin ac tortor orci. Nullam erat justo, bibendum at ultricies sed, mollis ut nunc. Nunc leo nunc, placerat ac elementum vel, luctus eget lacus. Nunc ultrices pulvinar nulla, eu viverra ligula aliquet vel. In ullamcorper risus risus, non efficitur nunc eleifend vitae. Nulla rutrum placerat nibh a laoreet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque in felis in risus ultricies tempor. Maecenas sit amet ornare diam. Praesent fermentum odio non aliquet euismod. Quisque commodo et lectus nec maximus. ",
      "slug": "product-22",
      "brand": "armaani",
      "rating": 5
    },
    {
      "id": 1023,
      "category": "Category 1",
      "name": "Product 23",
      "image": "https://picsum.photos/400?image=276",
      "stock": true,
      "price": "1304.242",
      "description": " Integer suscipit sapien magna, vitae hendrerit eros luctus ut. Quisque id suscipit augue, rutrum faucibus tortor. Proin ac tortor orci. Nullam erat justo, bibendum at ultricies sed, mollis ut nunc. Nunc leo nunc, placerat ac elementum vel, luctus eget lacus. Nunc ultrices pulvinar nulla, eu viverra ligula aliquet vel. In ullamcorper risus risus, non efficitur nunc eleifend vitae. Nulla rutrum placerat nibh a laoreet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque in felis in risus ultricies tempor. Maecenas sit amet ornare diam. Praesent fermentum odio non aliquet euismod. Quisque commodo et lectus nec maximus. ",
      "slug": "product-23",
      "brand": "armaani",
      "rating": 3
    },
    {
      "id": 1024,
      "category": "Category 4",
      "name": "Product 24",
      "image": "https://picsum.photos/400?image=66",
      "stock": true,
      "price": "2144.147",
      "description": " Integer suscipit sapien magna, vitae hendrerit eros luctus ut. Quisque id suscipit augue, rutrum faucibus tortor. Proin ac tortor orci. Nullam erat justo, bibendum at ultricies sed, mollis ut nunc. Nunc leo nunc, placerat ac elementum vel, luctus eget lacus. Nunc ultrices pulvinar nulla, eu viverra ligula aliquet vel. In ullamcorper risus risus, non efficitur nunc eleifend vitae. Nulla rutrum placerat nibh a laoreet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque in felis in risus ultricies tempor. Maecenas sit amet ornare diam. Praesent fermentum odio non aliquet euismod. Quisque commodo et lectus nec maximus. ",
      "slug": "product-24",
      "brand": "armaani",
      "rating": 4
    },
    {
      "id": 1025,
      "category": "Category 4",
      "name": "Product 25",
      "image": "https://picsum.photos/400?image=6",
      "stock": false,
      "price": "1351.723",
      "description": " Integer suscipit sapien magna, vitae hendrerit eros luctus ut. Quisque id suscipit augue, rutrum faucibus tortor. Proin ac tortor orci. Nullam erat justo, bibendum at ultricies sed, mollis ut nunc. Nunc leo nunc, placerat ac elementum vel, luctus eget lacus. Nunc ultrices pulvinar nulla, eu viverra ligula aliquet vel. In ullamcorper risus risus, non efficitur nunc eleifend vitae. Nulla rutrum placerat nibh a laoreet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque in felis in risus ultricies tempor. Maecenas sit amet ornare diam. Praesent fermentum odio non aliquet euismod. Quisque commodo et lectus nec maximus. ",
      "slug": "product-25",
      "brand": "armaani",
      "rating": 3
    },
    {
      "id": 1026,
      "category": "Category 2",
      "name": "Product 26",
      "image": "https://picsum.photos/400?image=158",
      "stock": false,
      "price": "1964.587",
      "description": " Integer suscipit sapien magna, vitae hendrerit eros luctus ut. Quisque id suscipit augue, rutrum faucibus tortor. Proin ac tortor orci. Nullam erat justo, bibendum at ultricies sed, mollis ut nunc. Nunc leo nunc, placerat ac elementum vel, luctus eget lacus. Nunc ultrices pulvinar nulla, eu viverra ligula aliquet vel. In ullamcorper risus risus, non efficitur nunc eleifend vitae. Nulla rutrum placerat nibh a laoreet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque in felis in risus ultricies tempor. Maecenas sit amet ornare diam. Praesent fermentum odio non aliquet euismod. Quisque commodo et lectus nec maximus. ",
      "slug": "product-26",
      "brand": "armaani",
      "rating": 4
    },
    {
      "id": 1027,
      "category": "Category 1",
      "name": "Product 27",
      "image": "https://picsum.photos/400?image=100",
      "stock": true,
      "price": "3412.277",
      "description": " Integer suscipit sapien magna, vitae hendrerit eros luctus ut. Quisque id suscipit augue, rutrum faucibus tortor. Proin ac tortor orci. Nullam erat justo, bibendum at ultricies sed, mollis ut nunc. Nunc leo nunc, placerat ac elementum vel, luctus eget lacus. Nunc ultrices pulvinar nulla, eu viverra ligula aliquet vel. In ullamcorper risus risus, non efficitur nunc eleifend vitae. Nulla rutrum placerat nibh a laoreet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque in felis in risus ultricies tempor. Maecenas sit amet ornare diam. Praesent fermentum odio non aliquet euismod. Quisque commodo et lectus nec maximus. ",
      "slug": "product-27",
      "brand": "armaani",
      "rating": 5
    },
    {
      "id": 1028,
      "category": "Category 2",
      "name": "Product 28",
      "image": "https://picsum.photos/400?image=184",
      "stock": true,
      "price": "1839.874",
      "description": " Integer suscipit sapien magna, vitae hendrerit eros luctus ut. Quisque id suscipit augue, rutrum faucibus tortor. Proin ac tortor orci. Nullam erat justo, bibendum at ultricies sed, mollis ut nunc. Nunc leo nunc, placerat ac elementum vel, luctus eget lacus. Nunc ultrices pulvinar nulla, eu viverra ligula aliquet vel. In ullamcorper risus risus, non efficitur nunc eleifend vitae. Nulla rutrum placerat nibh a laoreet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque in felis in risus ultricies tempor. Maecenas sit amet ornare diam. Praesent fermentum odio non aliquet euismod. Quisque commodo et lectus nec maximus. ",
      "slug": "product-28",
      "brand": "armaani",
      "rating": 4
    },
    {
      "id": 1029,
      "category": "Category 1",
      "name": "Product 29",
      "image": "https://picsum.photos/400?image=397",
      "stock": true,
      "price": "2663.447",
      "description": " Integer suscipit sapien magna, vitae hendrerit eros luctus ut. Quisque id suscipit augue, rutrum faucibus tortor. Proin ac tortor orci. Nullam erat justo, bibendum at ultricies sed, mollis ut nunc. Nunc leo nunc, placerat ac elementum vel, luctus eget lacus. Nunc ultrices pulvinar nulla, eu viverra ligula aliquet vel. In ullamcorper risus risus, non efficitur nunc eleifend vitae. Nulla rutrum placerat nibh a laoreet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque in felis in risus ultricies tempor. Maecenas sit amet ornare diam. Praesent fermentum odio non aliquet euismod. Quisque commodo et lectus nec maximus. ",
      "slug": "product-29",
      "brand": "armaani",
      "rating": 4
    },
    {
      "id": 1030,
      "category": "Category 1",
      "name": "Product 30",
      "image": "https://picsum.photos/400?image=420",
      "stock": false,
      "price": "3240.650",
      "description": " Integer suscipit sapien magna, vitae hendrerit eros luctus ut. Quisque id suscipit augue, rutrum faucibus tortor. Proin ac tortor orci. Nullam erat justo, bibendum at ultricies sed, mollis ut nunc. Nunc leo nunc, placerat ac elementum vel, luctus eget lacus. Nunc ultrices pulvinar nulla, eu viverra ligula aliquet vel. In ullamcorper risus risus, non efficitur nunc eleifend vitae. Nulla rutrum placerat nibh a laoreet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque in felis in risus ultricies tempor. Maecenas sit amet ornare diam. Praesent fermentum odio non aliquet euismod. Quisque commodo et lectus nec maximus. ",
      "slug": "product-30",
      "brand": "armaani",
      "rating": 5
    },
    {
      "id": 1031,
      "category": "Category 2",
      "name": "Product 31",
      "image": "https://picsum.photos/400?image=207",
      "stock": true,
      "price": "1024.704",
      "description": " Integer suscipit sapien magna, vitae hendrerit eros luctus ut. Quisque id suscipit augue, rutrum faucibus tortor. Proin ac tortor orci. Nullam erat justo, bibendum at ultricies sed, mollis ut nunc. Nunc leo nunc, placerat ac elementum vel, luctus eget lacus. Nunc ultrices pulvinar nulla, eu viverra ligula aliquet vel. In ullamcorper risus risus, non efficitur nunc eleifend vitae. Nulla rutrum placerat nibh a laoreet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque in felis in risus ultricies tempor. Maecenas sit amet ornare diam. Praesent fermentum odio non aliquet euismod. Quisque commodo et lectus nec maximus. ",
      "slug": "product-31",
      "brand": "armaani",
      "rating": 4
    },
    {
      "id": 1032,
      "category": "Category 2",
      "name": "Product 32",
      "image": "https://picsum.photos/400?image=729",
      "stock": false,
      "price": "2401.609",
      "description": " Integer suscipit sapien magna, vitae hendrerit eros luctus ut. Quisque id suscipit augue, rutrum faucibus tortor. Proin ac tortor orci. Nullam erat justo, bibendum at ultricies sed, mollis ut nunc. Nunc leo nunc, placerat ac elementum vel, luctus eget lacus. Nunc ultrices pulvinar nulla, eu viverra ligula aliquet vel. In ullamcorper risus risus, non efficitur nunc eleifend vitae. Nulla rutrum placerat nibh a laoreet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque in felis in risus ultricies tempor. Maecenas sit amet ornare diam. Praesent fermentum odio non aliquet euismod. Quisque commodo et lectus nec maximus. ",
      "slug": "product-32",
      "brand": "armaani",
      "rating": 4
    },
    {
      "id": 1033,
      "category": "Category 4",
      "name": "Product 33",
      "image": "https://picsum.photos/400?image=84",
      "stock": false,
      "price": "1559.786",
      "description": " Integer suscipit sapien magna, vitae hendrerit eros luctus ut. Quisque id suscipit augue, rutrum faucibus tortor. Proin ac tortor orci. Nullam erat justo, bibendum at ultricies sed, mollis ut nunc. Nunc leo nunc, placerat ac elementum vel, luctus eget lacus. Nunc ultrices pulvinar nulla, eu viverra ligula aliquet vel. In ullamcorper risus risus, non efficitur nunc eleifend vitae. Nulla rutrum placerat nibh a laoreet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque in felis in risus ultricies tempor. Maecenas sit amet ornare diam. Praesent fermentum odio non aliquet euismod. Quisque commodo et lectus nec maximus. ",
      "slug": "product-33",
      "brand": "armaani",
      "rating": 4
    },
    {
      "id": 1034,
      "category": "Category 1",
      "name": "Product 34",
      "image": "https://picsum.photos/400?image=48",
      "stock": true,
      "price": "2116.711",
      "description": " Integer suscipit sapien magna, vitae hendrerit eros luctus ut. Quisque id suscipit augue, rutrum faucibus tortor. Proin ac tortor orci. Nullam erat justo, bibendum at ultricies sed, mollis ut nunc. Nunc leo nunc, placerat ac elementum vel, luctus eget lacus. Nunc ultrices pulvinar nulla, eu viverra ligula aliquet vel. In ullamcorper risus risus, non efficitur nunc eleifend vitae. Nulla rutrum placerat nibh a laoreet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque in felis in risus ultricies tempor. Maecenas sit amet ornare diam. Praesent fermentum odio non aliquet euismod. Quisque commodo et lectus nec maximus. ",
      "slug": "product-34",
      "brand": "armaani",
      "rating": 3
    },
    {
      "id": 1035,
      "category": "Category 4",
      "name": "Product 35",
      "image": "https://picsum.photos/400?image=999",
      "stock": false,
      "price": "1000.066",
      "description": " Integer suscipit sapien magna, vitae hendrerit eros luctus ut. Quisque id suscipit augue, rutrum faucibus tortor. Proin ac tortor orci. Nullam erat justo, bibendum at ultricies sed, mollis ut nunc. Nunc leo nunc, placerat ac elementum vel, luctus eget lacus. Nunc ultrices pulvinar nulla, eu viverra ligula aliquet vel. In ullamcorper risus risus, non efficitur nunc eleifend vitae. Nulla rutrum placerat nibh a laoreet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque in felis in risus ultricies tempor. Maecenas sit amet ornare diam. Praesent fermentum odio non aliquet euismod. Quisque commodo et lectus nec maximus. ",
      "slug": "product-35",
      "brand": "armaani",
      "rating": 3
    },
    {
      "id": 1036,
      "category": "Category 2",
      "name": "Product 36",
      "image": "https://picsum.photos/400?image=812",
      "stock": false,
      "price": "3049.418",
      "description": " Integer suscipit sapien magna, vitae hendrerit eros luctus ut. Quisque id suscipit augue, rutrum faucibus tortor. Proin ac tortor orci. Nullam erat justo, bibendum at ultricies sed, mollis ut nunc. Nunc leo nunc, placerat ac elementum vel, luctus eget lacus. Nunc ultrices pulvinar nulla, eu viverra ligula aliquet vel. In ullamcorper risus risus, non efficitur nunc eleifend vitae. Nulla rutrum placerat nibh a laoreet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque in felis in risus ultricies tempor. Maecenas sit amet ornare diam. Praesent fermentum odio non aliquet euismod. Quisque commodo et lectus nec maximus. ",
      "slug": "product-36",
      "brand": "armaani",
      "rating": 3
    },
    {
      "id": 1037,
      "category": "Category 2",
      "name": "Product 37",
      "image": "https://picsum.photos/400?image=927",
      "stock": true,
      "price": "1853.454",
      "description": " Integer suscipit sapien magna, vitae hendrerit eros luctus ut. Quisque id suscipit augue, rutrum faucibus tortor. Proin ac tortor orci. Nullam erat justo, bibendum at ultricies sed, mollis ut nunc. Nunc leo nunc, placerat ac elementum vel, luctus eget lacus. Nunc ultrices pulvinar nulla, eu viverra ligula aliquet vel. In ullamcorper risus risus, non efficitur nunc eleifend vitae. Nulla rutrum placerat nibh a laoreet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque in felis in risus ultricies tempor. Maecenas sit amet ornare diam. Praesent fermentum odio non aliquet euismod. Quisque commodo et lectus nec maximus. ",
      "slug": "product-37",
      "brand": "armaani",
      "rating": 3
    },
    {
      "id": 1038,
      "category": "Category 3",
      "name": "Product 38",
      "image": "https://picsum.photos/400?image=305",
      "stock": false,
      "price": "2323.186",
      "description": " Integer suscipit sapien magna, vitae hendrerit eros luctus ut. Quisque id suscipit augue, rutrum faucibus tortor. Proin ac tortor orci. Nullam erat justo, bibendum at ultricies sed, mollis ut nunc. Nunc leo nunc, placerat ac elementum vel, luctus eget lacus. Nunc ultrices pulvinar nulla, eu viverra ligula aliquet vel. In ullamcorper risus risus, non efficitur nunc eleifend vitae. Nulla rutrum placerat nibh a laoreet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque in felis in risus ultricies tempor. Maecenas sit amet ornare diam. Praesent fermentum odio non aliquet euismod. Quisque commodo et lectus nec maximus. ",
      "slug": "product-38",
      "brand": "armaani",
      "rating": 3
    },
    {
      "id": 1039,
      "category": "Category 4",
      "name": "Product 39",
      "image": "https://picsum.photos/400?image=274",
      "stock": false,
      "price": "2326.058",
      "description": " Integer suscipit sapien magna, vitae hendrerit eros luctus ut. Quisque id suscipit augue, rutrum faucibus tortor. Proin ac tortor orci. Nullam erat justo, bibendum at ultricies sed, mollis ut nunc. Nunc leo nunc, placerat ac elementum vel, luctus eget lacus. Nunc ultrices pulvinar nulla, eu viverra ligula aliquet vel. In ullamcorper risus risus, non efficitur nunc eleifend vitae. Nulla rutrum placerat nibh a laoreet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque in felis in risus ultricies tempor. Maecenas sit amet ornare diam. Praesent fermentum odio non aliquet euismod. Quisque commodo et lectus nec maximus. ",
      "slug": "product-39",
      "brand": "armaani",
      "rating": 4
    },
    {
      "id": 1040,
      "category": "Category 2",
      "name": "Product 40",
      "image": "https://picsum.photos/400?image=229",
      "stock": false,
      "price": "1826.365",
      "description": " Integer suscipit sapien magna, vitae hendrerit eros luctus ut. Quisque id suscipit augue, rutrum faucibus tortor. Proin ac tortor orci. Nullam erat justo, bibendum at ultricies sed, mollis ut nunc. Nunc leo nunc, placerat ac elementum vel, luctus eget lacus. Nunc ultrices pulvinar nulla, eu viverra ligula aliquet vel. In ullamcorper risus risus, non efficitur nunc eleifend vitae. Nulla rutrum placerat nibh a laoreet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque in felis in risus ultricies tempor. Maecenas sit amet ornare diam. Praesent fermentum odio non aliquet euismod. Quisque commodo et lectus nec maximus. ",
      "slug": "product-40",
      "brand": "armaani",
      "rating": 4
    },
    {
      "id": 1041,
      "category": "Category 1",
      "name": "Product 41",
      "image": "https://picsum.photos/400?image=739",
      "stock": true,
      "price": "1070.979",
      "description": " Integer suscipit sapien magna, vitae hendrerit eros luctus ut. Quisque id suscipit augue, rutrum faucibus tortor. Proin ac tortor orci. Nullam erat justo, bibendum at ultricies sed, mollis ut nunc. Nunc leo nunc, placerat ac elementum vel, luctus eget lacus. Nunc ultrices pulvinar nulla, eu viverra ligula aliquet vel. In ullamcorper risus risus, non efficitur nunc eleifend vitae. Nulla rutrum placerat nibh a laoreet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque in felis in risus ultricies tempor. Maecenas sit amet ornare diam. Praesent fermentum odio non aliquet euismod. Quisque commodo et lectus nec maximus. ",
      "slug": "product-41",
      "brand": "armaani",
      "rating": 3
    },
    {
      "id": 1042,
      "category": "Category 3",
      "name": "Product 42",
      "image": "https://picsum.photos/400?image=91",
      "stock": true,
      "price": "2312.837",
      "description": " Integer suscipit sapien magna, vitae hendrerit eros luctus ut. Quisque id suscipit augue, rutrum faucibus tortor. Proin ac tortor orci. Nullam erat justo, bibendum at ultricies sed, mollis ut nunc. Nunc leo nunc, placerat ac elementum vel, luctus eget lacus. Nunc ultrices pulvinar nulla, eu viverra ligula aliquet vel. In ullamcorper risus risus, non efficitur nunc eleifend vitae. Nulla rutrum placerat nibh a laoreet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque in felis in risus ultricies tempor. Maecenas sit amet ornare diam. Praesent fermentum odio non aliquet euismod. Quisque commodo et lectus nec maximus. ",
      "slug": "product-42",
      "brand": "armaani",
      "rating": 5
    },
    {
      "id": 1043,
      "category": "Category 4",
      "name": "Product 43",
      "image": "https://picsum.photos/400?image=411",
      "stock": true,
      "price": "1718.721",
      "description": " Integer suscipit sapien magna, vitae hendrerit eros luctus ut. Quisque id suscipit augue, rutrum faucibus tortor. Proin ac tortor orci. Nullam erat justo, bibendum at ultricies sed, mollis ut nunc. Nunc leo nunc, placerat ac elementum vel, luctus eget lacus. Nunc ultrices pulvinar nulla, eu viverra ligula aliquet vel. In ullamcorper risus risus, non efficitur nunc eleifend vitae. Nulla rutrum placerat nibh a laoreet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque in felis in risus ultricies tempor. Maecenas sit amet ornare diam. Praesent fermentum odio non aliquet euismod. Quisque commodo et lectus nec maximus. ",
      "slug": "product-43",
      "brand": "armaani",
      "rating": 4
    },
    {
      "id": 1044,
      "category": "Category 4",
      "name": "Product 44",
      "image": "https://picsum.photos/400?image=111",
      "stock": false,
      "price": "1996.659",
      "description": " Integer suscipit sapien magna, vitae hendrerit eros luctus ut. Quisque id suscipit augue, rutrum faucibus tortor. Proin ac tortor orci. Nullam erat justo, bibendum at ultricies sed, mollis ut nunc. Nunc leo nunc, placerat ac elementum vel, luctus eget lacus. Nunc ultrices pulvinar nulla, eu viverra ligula aliquet vel. In ullamcorper risus risus, non efficitur nunc eleifend vitae. Nulla rutrum placerat nibh a laoreet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque in felis in risus ultricies tempor. Maecenas sit amet ornare diam. Praesent fermentum odio non aliquet euismod. Quisque commodo et lectus nec maximus. ",
      "slug": "product-44",
      "brand": "armaani",
      "rating": 3
    },
    {
      "id": 1045,
      "category": "Category 1",
      "name": "Product 45",
      "image": "https://picsum.photos/400?image=22",
      "stock": true,
      "price": "3424.445",
      "description": " Integer suscipit sapien magna, vitae hendrerit eros luctus ut. Quisque id suscipit augue, rutrum faucibus tortor. Proin ac tortor orci. Nullam erat justo, bibendum at ultricies sed, mollis ut nunc. Nunc leo nunc, placerat ac elementum vel, luctus eget lacus. Nunc ultrices pulvinar nulla, eu viverra ligula aliquet vel. In ullamcorper risus risus, non efficitur nunc eleifend vitae. Nulla rutrum placerat nibh a laoreet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque in felis in risus ultricies tempor. Maecenas sit amet ornare diam. Praesent fermentum odio non aliquet euismod. Quisque commodo et lectus nec maximus. ",
      "slug": "product-45",
      "brand": "armaani",
      "rating": 4
    },
    {
      "id": 1046,
      "category": "Category 1",
      "name": "Product 46",
      "image": "https://picsum.photos/400?image=88",
      "stock": false,
      "price": "2135.804",
      "description": " Integer suscipit sapien magna, vitae hendrerit eros luctus ut. Quisque id suscipit augue, rutrum faucibus tortor. Proin ac tortor orci. Nullam erat justo, bibendum at ultricies sed, mollis ut nunc. Nunc leo nunc, placerat ac elementum vel, luctus eget lacus. Nunc ultrices pulvinar nulla, eu viverra ligula aliquet vel. In ullamcorper risus risus, non efficitur nunc eleifend vitae. Nulla rutrum placerat nibh a laoreet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque in felis in risus ultricies tempor. Maecenas sit amet ornare diam. Praesent fermentum odio non aliquet euismod. Quisque commodo et lectus nec maximus. ",
      "slug": "product-46",
      "brand": "armaani",
      "rating": 4
    },
    {
      "id": 1047,
      "category": "Category 4",
      "name": "Product 47",
      "image": "https://picsum.photos/400?image=249",
      "stock": true,
      "price": "3856.436",
      "description": " Integer suscipit sapien magna, vitae hendrerit eros luctus ut. Quisque id suscipit augue, rutrum faucibus tortor. Proin ac tortor orci. Nullam erat justo, bibendum at ultricies sed, mollis ut nunc. Nunc leo nunc, placerat ac elementum vel, luctus eget lacus. Nunc ultrices pulvinar nulla, eu viverra ligula aliquet vel. In ullamcorper risus risus, non efficitur nunc eleifend vitae. Nulla rutrum placerat nibh a laoreet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque in felis in risus ultricies tempor. Maecenas sit amet ornare diam. Praesent fermentum odio non aliquet euismod. Quisque commodo et lectus nec maximus. ",
      "slug": "product-47",
      "brand": "armaani",
      "rating": 4
    },
    {
      "id": 1048,
      "category": "Category 1",
      "name": "Product 48",
      "image": "https://picsum.photos/400?image=579",
      "stock": true,
      "price": "3067.335",
      "description": " Integer suscipit sapien magna, vitae hendrerit eros luctus ut. Quisque id suscipit augue, rutrum faucibus tortor. Proin ac tortor orci. Nullam erat justo, bibendum at ultricies sed, mollis ut nunc. Nunc leo nunc, placerat ac elementum vel, luctus eget lacus. Nunc ultrices pulvinar nulla, eu viverra ligula aliquet vel. In ullamcorper risus risus, non efficitur nunc eleifend vitae. Nulla rutrum placerat nibh a laoreet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque in felis in risus ultricies tempor. Maecenas sit amet ornare diam. Praesent fermentum odio non aliquet euismod. Quisque commodo et lectus nec maximus. ",
      "slug": "product-48",
      "brand": "armaani",
      "rating": 4
    },
    {
      "id": 1049,
      "category": "Category 1",
      "name": "Product 49",
      "image": "https://picsum.photos/400?image=488",
      "stock": true,
      "price": "3752.545",
      "description": " Integer suscipit sapien magna, vitae hendrerit eros luctus ut. Quisque id suscipit augue, rutrum faucibus tortor. Proin ac tortor orci. Nullam erat justo, bibendum at ultricies sed, mollis ut nunc. Nunc leo nunc, placerat ac elementum vel, luctus eget lacus. Nunc ultrices pulvinar nulla, eu viverra ligula aliquet vel. In ullamcorper risus risus, non efficitur nunc eleifend vitae. Nulla rutrum placerat nibh a laoreet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque in felis in risus ultricies tempor. Maecenas sit amet ornare diam. Praesent fermentum odio non aliquet euismod. Quisque commodo et lectus nec maximus. ",
      "slug": "product-49",
      "brand": "armaani",
      "rating": 4
    },
    {
      "id": 1050,
      "category": "Category 4",
      "name": "Product 50",
      "image": "https://picsum.photos/400?image=842",
      "stock": false,
      "price": "3245.773",
      "description": " Integer suscipit sapien magna, vitae hendrerit eros luctus ut. Quisque id suscipit augue, rutrum faucibus tortor. Proin ac tortor orci. Nullam erat justo, bibendum at ultricies sed, mollis ut nunc. Nunc leo nunc, placerat ac elementum vel, luctus eget lacus. Nunc ultrices pulvinar nulla, eu viverra ligula aliquet vel. In ullamcorper risus risus, non efficitur nunc eleifend vitae. Nulla rutrum placerat nibh a laoreet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque in felis in risus ultricies tempor. Maecenas sit amet ornare diam. Praesent fermentum odio non aliquet euismod. Quisque commodo et lectus nec maximus. ",
      "slug": "product-50",
      "brand": "armaani",
      "rating": 4
    },
    {
      "id": 1051,
      "category": "Category 1",
      "name": "Product 51",
      "image": "https://picsum.photos/400?image=113",
      "stock": true,
      "price": "2752.827",
      "description": " Integer suscipit sapien magna, vitae hendrerit eros luctus ut. Quisque id suscipit augue, rutrum faucibus tortor. Proin ac tortor orci. Nullam erat justo, bibendum at ultricies sed, mollis ut nunc. Nunc leo nunc, placerat ac elementum vel, luctus eget lacus. Nunc ultrices pulvinar nulla, eu viverra ligula aliquet vel. In ullamcorper risus risus, non efficitur nunc eleifend vitae. Nulla rutrum placerat nibh a laoreet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque in felis in risus ultricies tempor. Maecenas sit amet ornare diam. Praesent fermentum odio non aliquet euismod. Quisque commodo et lectus nec maximus. ",
      "slug": "product-51",
      "brand": "armaani",
      "rating": 4
    },
    {
      "id": 1052,
      "category": "Category 1",
      "name": "Product 52",
      "image": "https://picsum.photos/400?image=562",
      "stock": true,
      "price": "1630.670",
      "description": " Integer suscipit sapien magna, vitae hendrerit eros luctus ut. Quisque id suscipit augue, rutrum faucibus tortor. Proin ac tortor orci. Nullam erat justo, bibendum at ultricies sed, mollis ut nunc. Nunc leo nunc, placerat ac elementum vel, luctus eget lacus. Nunc ultrices pulvinar nulla, eu viverra ligula aliquet vel. In ullamcorper risus risus, non efficitur nunc eleifend vitae. Nulla rutrum placerat nibh a laoreet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque in felis in risus ultricies tempor. Maecenas sit amet ornare diam. Praesent fermentum odio non aliquet euismod. Quisque commodo et lectus nec maximus. ",
      "slug": "product-52",
      "brand": "armaani",
      "rating": 5
    },
    {
      "id": 1053,
      "category": "Category 2",
      "name": "Product 53",
      "image": "https://picsum.photos/400?image=114",
      "stock": true,
      "price": "1824.373",
      "description": " Integer suscipit sapien magna, vitae hendrerit eros luctus ut. Quisque id suscipit augue, rutrum faucibus tortor. Proin ac tortor orci. Nullam erat justo, bibendum at ultricies sed, mollis ut nunc. Nunc leo nunc, placerat ac elementum vel, luctus eget lacus. Nunc ultrices pulvinar nulla, eu viverra ligula aliquet vel. In ullamcorper risus risus, non efficitur nunc eleifend vitae. Nulla rutrum placerat nibh a laoreet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque in felis in risus ultricies tempor. Maecenas sit amet ornare diam. Praesent fermentum odio non aliquet euismod. Quisque commodo et lectus nec maximus. ",
      "slug": "product-53",
      "brand": "armaani",
      "rating": 4
    },
    {
      "id": 1054,
      "category": "Category 4",
      "name": "Product 54",
      "image": "https://picsum.photos/400?image=396",
      "stock": true,
      "price": "1786.785",
      "description": " Integer suscipit sapien magna, vitae hendrerit eros luctus ut. Quisque id suscipit augue, rutrum faucibus tortor. Proin ac tortor orci. Nullam erat justo, bibendum at ultricies sed, mollis ut nunc. Nunc leo nunc, placerat ac elementum vel, luctus eget lacus. Nunc ultrices pulvinar nulla, eu viverra ligula aliquet vel. In ullamcorper risus risus, non efficitur nunc eleifend vitae. Nulla rutrum placerat nibh a laoreet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque in felis in risus ultricies tempor. Maecenas sit amet ornare diam. Praesent fermentum odio non aliquet euismod. Quisque commodo et lectus nec maximus. ",
      "slug": "product-54",
      "brand": "armaani",
      "rating": 4
    },
    {
      "id": 1055,
      "category": "Category 4",
      "name": "Product 55",
      "image": "https://picsum.photos/400?image=357",
      "stock": true,
      "price": "2220.931",
      "description": " Integer suscipit sapien magna, vitae hendrerit eros luctus ut. Quisque id suscipit augue, rutrum faucibus tortor. Proin ac tortor orci. Nullam erat justo, bibendum at ultricies sed, mollis ut nunc. Nunc leo nunc, placerat ac elementum vel, luctus eget lacus. Nunc ultrices pulvinar nulla, eu viverra ligula aliquet vel. In ullamcorper risus risus, non efficitur nunc eleifend vitae. Nulla rutrum placerat nibh a laoreet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque in felis in risus ultricies tempor. Maecenas sit amet ornare diam. Praesent fermentum odio non aliquet euismod. Quisque commodo et lectus nec maximus. ",
      "slug": "product-55",
      "brand": "armaani",
      "rating": 4
    },
    {
      "id": 1056,
      "category": "Category 2",
      "name": "Product 56",
      "image": "https://picsum.photos/400?image=330",
      "stock": true,
      "price": "2840.721",
      "description": " Integer suscipit sapien magna, vitae hendrerit eros luctus ut. Quisque id suscipit augue, rutrum faucibus tortor. Proin ac tortor orci. Nullam erat justo, bibendum at ultricies sed, mollis ut nunc. Nunc leo nunc, placerat ac elementum vel, luctus eget lacus. Nunc ultrices pulvinar nulla, eu viverra ligula aliquet vel. In ullamcorper risus risus, non efficitur nunc eleifend vitae. Nulla rutrum placerat nibh a laoreet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque in felis in risus ultricies tempor. Maecenas sit amet ornare diam. Praesent fermentum odio non aliquet euismod. Quisque commodo et lectus nec maximus. ",
      "slug": "product-56",
      "brand": "armaani",
      "rating": 4
    },
    {
      "id": 1057,
      "category": "Category 4",
      "name": "Product 57",
      "image": "https://picsum.photos/400?image=858",
      "stock": false,
      "price": "3218.239",
      "description": " Integer suscipit sapien magna, vitae hendrerit eros luctus ut. Quisque id suscipit augue, rutrum faucibus tortor. Proin ac tortor orci. Nullam erat justo, bibendum at ultricies sed, mollis ut nunc. Nunc leo nunc, placerat ac elementum vel, luctus eget lacus. Nunc ultrices pulvinar nulla, eu viverra ligula aliquet vel. In ullamcorper risus risus, non efficitur nunc eleifend vitae. Nulla rutrum placerat nibh a laoreet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque in felis in risus ultricies tempor. Maecenas sit amet ornare diam. Praesent fermentum odio non aliquet euismod. Quisque commodo et lectus nec maximus. ",
      "slug": "product-57",
      "brand": "armaani",
      "rating": 4
    },
    {
      "id": 1058,
      "category": "Category 1",
      "name": "Product 58",
      "image": "https://picsum.photos/400?image=980",
      "stock": true,
      "price": "2062.977",
      "description": " Integer suscipit sapien magna, vitae hendrerit eros luctus ut. Quisque id suscipit augue, rutrum faucibus tortor. Proin ac tortor orci. Nullam erat justo, bibendum at ultricies sed, mollis ut nunc. Nunc leo nunc, placerat ac elementum vel, luctus eget lacus. Nunc ultrices pulvinar nulla, eu viverra ligula aliquet vel. In ullamcorper risus risus, non efficitur nunc eleifend vitae. Nulla rutrum placerat nibh a laoreet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque in felis in risus ultricies tempor. Maecenas sit amet ornare diam. Praesent fermentum odio non aliquet euismod. Quisque commodo et lectus nec maximus. ",
      "slug": "product-58",
      "brand": "armaani",
      "rating": 4
    },
    {
      "id": 1059,
      "category": "Category 1",
      "name": "Product 59",
      "image": "https://picsum.photos/400?image=66",
      "stock": true,
      "price": "2080.868",
      "description": " Integer suscipit sapien magna, vitae hendrerit eros luctus ut. Quisque id suscipit augue, rutrum faucibus tortor. Proin ac tortor orci. Nullam erat justo, bibendum at ultricies sed, mollis ut nunc. Nunc leo nunc, placerat ac elementum vel, luctus eget lacus. Nunc ultrices pulvinar nulla, eu viverra ligula aliquet vel. In ullamcorper risus risus, non efficitur nunc eleifend vitae. Nulla rutrum placerat nibh a laoreet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque in felis in risus ultricies tempor. Maecenas sit amet ornare diam. Praesent fermentum odio non aliquet euismod. Quisque commodo et lectus nec maximus. ",
      "slug": "product-59",
      "brand": "armaani",
      "rating": 4
    },
    {
      "id": 1060,
      "category": "Category 2",
      "name": "Product 60",
      "image": "https://picsum.photos/400?image=169",
      "stock": false,
      "price": "2262.350",
      "description": " Integer suscipit sapien magna, vitae hendrerit eros luctus ut. Quisque id suscipit augue, rutrum faucibus tortor. Proin ac tortor orci. Nullam erat justo, bibendum at ultricies sed, mollis ut nunc. Nunc leo nunc, placerat ac elementum vel, luctus eget lacus. Nunc ultrices pulvinar nulla, eu viverra ligula aliquet vel. In ullamcorper risus risus, non efficitur nunc eleifend vitae. Nulla rutrum placerat nibh a laoreet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque in felis in risus ultricies tempor. Maecenas sit amet ornare diam. Praesent fermentum odio non aliquet euismod. Quisque commodo et lectus nec maximus. ",
      "slug": "product-60",
      "brand": "armaani",
      "rating": 4
    },
    {
      "id": 1061,
      "category": "Category 3",
      "name": "Product 61",
      "image": "https://picsum.photos/400?image=682",
      "stock": true,
      "price": "2448.157",
      "description": " Integer suscipit sapien magna, vitae hendrerit eros luctus ut. Quisque id suscipit augue, rutrum faucibus tortor. Proin ac tortor orci. Nullam erat justo, bibendum at ultricies sed, mollis ut nunc. Nunc leo nunc, placerat ac elementum vel, luctus eget lacus. Nunc ultrices pulvinar nulla, eu viverra ligula aliquet vel. In ullamcorper risus risus, non efficitur nunc eleifend vitae. Nulla rutrum placerat nibh a laoreet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque in felis in risus ultricies tempor. Maecenas sit amet ornare diam. Praesent fermentum odio non aliquet euismod. Quisque commodo et lectus nec maximus. ",
      "slug": "product-61",
      "brand": "armaani",
      "rating": 4
    },
    {
      "id": 1062,
      "category": "Category 1",
      "name": "Product 62",
      "image": "https://picsum.photos/400?image=925",
      "stock": false,
      "price": "2752.909",
      "description": " Integer suscipit sapien magna, vitae hendrerit eros luctus ut. Quisque id suscipit augue, rutrum faucibus tortor. Proin ac tortor orci. Nullam erat justo, bibendum at ultricies sed, mollis ut nunc. Nunc leo nunc, placerat ac elementum vel, luctus eget lacus. Nunc ultrices pulvinar nulla, eu viverra ligula aliquet vel. In ullamcorper risus risus, non efficitur nunc eleifend vitae. Nulla rutrum placerat nibh a laoreet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque in felis in risus ultricies tempor. Maecenas sit amet ornare diam. Praesent fermentum odio non aliquet euismod. Quisque commodo et lectus nec maximus. ",
      "slug": "product-62",
      "brand": "armaani",
      "rating": 4
    },
    {
      "id": 1063,
      "category": "Category 1",
      "name": "Product 63",
      "image": "https://picsum.photos/400?image=190",
      "stock": false,
      "price": "1613.234",
      "description": " Integer suscipit sapien magna, vitae hendrerit eros luctus ut. Quisque id suscipit augue, rutrum faucibus tortor. Proin ac tortor orci. Nullam erat justo, bibendum at ultricies sed, mollis ut nunc. Nunc leo nunc, placerat ac elementum vel, luctus eget lacus. Nunc ultrices pulvinar nulla, eu viverra ligula aliquet vel. In ullamcorper risus risus, non efficitur nunc eleifend vitae. Nulla rutrum placerat nibh a laoreet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque in felis in risus ultricies tempor. Maecenas sit amet ornare diam. Praesent fermentum odio non aliquet euismod. Quisque commodo et lectus nec maximus. ",
      "slug": "product-63",
      "brand": "armaani",
      "rating": 5
    },
    {
      "id": 1064,
      "category": "Category 3",
      "name": "Product 64",
      "image": "https://picsum.photos/400?image=809",
      "stock": true,
      "price": "2639.061",
      "description": " Integer suscipit sapien magna, vitae hendrerit eros luctus ut. Quisque id suscipit augue, rutrum faucibus tortor. Proin ac tortor orci. Nullam erat justo, bibendum at ultricies sed, mollis ut nunc. Nunc leo nunc, placerat ac elementum vel, luctus eget lacus. Nunc ultrices pulvinar nulla, eu viverra ligula aliquet vel. In ullamcorper risus risus, non efficitur nunc eleifend vitae. Nulla rutrum placerat nibh a laoreet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque in felis in risus ultricies tempor. Maecenas sit amet ornare diam. Praesent fermentum odio non aliquet euismod. Quisque commodo et lectus nec maximus. ",
      "slug": "product-64",
      "brand": "armaani",
      "rating": 5
    },
    {
      "id": 1065,
      "category": "Category 4",
      "name": "Product 65",
      "image": "https://picsum.photos/400?image=648",
      "stock": false,
      "price": "2264.889",
      "description": " Integer suscipit sapien magna, vitae hendrerit eros luctus ut. Quisque id suscipit augue, rutrum faucibus tortor. Proin ac tortor orci. Nullam erat justo, bibendum at ultricies sed, mollis ut nunc. Nunc leo nunc, placerat ac elementum vel, luctus eget lacus. Nunc ultrices pulvinar nulla, eu viverra ligula aliquet vel. In ullamcorper risus risus, non efficitur nunc eleifend vitae. Nulla rutrum placerat nibh a laoreet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque in felis in risus ultricies tempor. Maecenas sit amet ornare diam. Praesent fermentum odio non aliquet euismod. Quisque commodo et lectus nec maximus. ",
      "slug": "product-65",
      "brand": "armaani",
      "rating": 4
    },
    {
      "id": 1066,
      "category": "Category 2",
      "name": "Product 66",
      "image": "https://picsum.photos/400?image=963",
      "stock": true,
      "price": "1700.558",
      "description": " Integer suscipit sapien magna, vitae hendrerit eros luctus ut. Quisque id suscipit augue, rutrum faucibus tortor. Proin ac tortor orci. Nullam erat justo, bibendum at ultricies sed, mollis ut nunc. Nunc leo nunc, placerat ac elementum vel, luctus eget lacus. Nunc ultrices pulvinar nulla, eu viverra ligula aliquet vel. In ullamcorper risus risus, non efficitur nunc eleifend vitae. Nulla rutrum placerat nibh a laoreet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque in felis in risus ultricies tempor. Maecenas sit amet ornare diam. Praesent fermentum odio non aliquet euismod. Quisque commodo et lectus nec maximus. ",
      "slug": "product-66",
      "brand": "armaani",
      "rating": 4
    },
    {
      "id": 1067,
      "category": "Category 3",
      "name": "Product 67",
      "image": "https://picsum.photos/400?image=598",
      "stock": false,
      "price": "3820.646",
      "description": " Integer suscipit sapien magna, vitae hendrerit eros luctus ut. Quisque id suscipit augue, rutrum faucibus tortor. Proin ac tortor orci. Nullam erat justo, bibendum at ultricies sed, mollis ut nunc. Nunc leo nunc, placerat ac elementum vel, luctus eget lacus. Nunc ultrices pulvinar nulla, eu viverra ligula aliquet vel. In ullamcorper risus risus, non efficitur nunc eleifend vitae. Nulla rutrum placerat nibh a laoreet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque in felis in risus ultricies tempor. Maecenas sit amet ornare diam. Praesent fermentum odio non aliquet euismod. Quisque commodo et lectus nec maximus. ",
      "slug": "product-67",
      "brand": "armaani",
      "rating": 3
    },
    {
      "id": 1068,
      "category": "Category 3",
      "name": "Product 68",
      "image": "https://picsum.photos/400?image=370",
      "stock": true,
      "price": "3506.979",
      "description": " Integer suscipit sapien magna, vitae hendrerit eros luctus ut. Quisque id suscipit augue, rutrum faucibus tortor. Proin ac tortor orci. Nullam erat justo, bibendum at ultricies sed, mollis ut nunc. Nunc leo nunc, placerat ac elementum vel, luctus eget lacus. Nunc ultrices pulvinar nulla, eu viverra ligula aliquet vel. In ullamcorper risus risus, non efficitur nunc eleifend vitae. Nulla rutrum placerat nibh a laoreet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque in felis in risus ultricies tempor. Maecenas sit amet ornare diam. Praesent fermentum odio non aliquet euismod. Quisque commodo et lectus nec maximus. ",
      "slug": "product-68",
      "brand": "armaani",
      "rating": 4
    },
    {
      "id": 1069,
      "category": "Category 1",
      "name": "Product 69",
      "image": "https://picsum.photos/400?image=19",
      "stock": false,
      "price": "1507.749",
      "description": " Integer suscipit sapien magna, vitae hendrerit eros luctus ut. Quisque id suscipit augue, rutrum faucibus tortor. Proin ac tortor orci. Nullam erat justo, bibendum at ultricies sed, mollis ut nunc. Nunc leo nunc, placerat ac elementum vel, luctus eget lacus. Nunc ultrices pulvinar nulla, eu viverra ligula aliquet vel. In ullamcorper risus risus, non efficitur nunc eleifend vitae. Nulla rutrum placerat nibh a laoreet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque in felis in risus ultricies tempor. Maecenas sit amet ornare diam. Praesent fermentum odio non aliquet euismod. Quisque commodo et lectus nec maximus. ",
      "slug": "product-69",
      "brand": "armaani",
      "rating": 3
    },
    {
      "id": 1070,
      "category": "Category 4",
      "name": "Product 70",
      "image": "https://picsum.photos/400?image=568",
      "stock": false,
      "price": "3435.209",
      "description": " Integer suscipit sapien magna, vitae hendrerit eros luctus ut. Quisque id suscipit augue, rutrum faucibus tortor. Proin ac tortor orci. Nullam erat justo, bibendum at ultricies sed, mollis ut nunc. Nunc leo nunc, placerat ac elementum vel, luctus eget lacus. Nunc ultrices pulvinar nulla, eu viverra ligula aliquet vel. In ullamcorper risus risus, non efficitur nunc eleifend vitae. Nulla rutrum placerat nibh a laoreet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque in felis in risus ultricies tempor. Maecenas sit amet ornare diam. Praesent fermentum odio non aliquet euismod. Quisque commodo et lectus nec maximus. ",
      "slug": "product-70",
      "brand": "armaani",
      "rating": 3
    },
    {
      "id": 1071,
      "category": "Category 3",
      "name": "Product 71",
      "image": "https://picsum.photos/400?image=516",
      "stock": false,
      "price": "3242.938",
      "description": " Integer suscipit sapien magna, vitae hendrerit eros luctus ut. Quisque id suscipit augue, rutrum faucibus tortor. Proin ac tortor orci. Nullam erat justo, bibendum at ultricies sed, mollis ut nunc. Nunc leo nunc, placerat ac elementum vel, luctus eget lacus. Nunc ultrices pulvinar nulla, eu viverra ligula aliquet vel. In ullamcorper risus risus, non efficitur nunc eleifend vitae. Nulla rutrum placerat nibh a laoreet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque in felis in risus ultricies tempor. Maecenas sit amet ornare diam. Praesent fermentum odio non aliquet euismod. Quisque commodo et lectus nec maximus. ",
      "slug": "product-71",
      "brand": "armaani",
      "rating": 4
    },
    {
      "id": 1072,
      "category": "Category 4",
      "name": "Product 72",
      "image": "https://picsum.photos/400?image=304",
      "stock": true,
      "price": "1073.736",
      "description": " Integer suscipit sapien magna, vitae hendrerit eros luctus ut. Quisque id suscipit augue, rutrum faucibus tortor. Proin ac tortor orci. Nullam erat justo, bibendum at ultricies sed, mollis ut nunc. Nunc leo nunc, placerat ac elementum vel, luctus eget lacus. Nunc ultrices pulvinar nulla, eu viverra ligula aliquet vel. In ullamcorper risus risus, non efficitur nunc eleifend vitae. Nulla rutrum placerat nibh a laoreet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque in felis in risus ultricies tempor. Maecenas sit amet ornare diam. Praesent fermentum odio non aliquet euismod. Quisque commodo et lectus nec maximus. ",
      "slug": "product-72",
      "brand": "armaani",
      "rating": 5
    },
    {
      "id": 1073,
      "category": "Category 1",
      "name": "Product 73",
      "image": "https://picsum.photos/400?image=889",
      "stock": true,
      "price": "2682.922",
      "description": " Integer suscipit sapien magna, vitae hendrerit eros luctus ut. Quisque id suscipit augue, rutrum faucibus tortor. Proin ac tortor orci. Nullam erat justo, bibendum at ultricies sed, mollis ut nunc. Nunc leo nunc, placerat ac elementum vel, luctus eget lacus. Nunc ultrices pulvinar nulla, eu viverra ligula aliquet vel. In ullamcorper risus risus, non efficitur nunc eleifend vitae. Nulla rutrum placerat nibh a laoreet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque in felis in risus ultricies tempor. Maecenas sit amet ornare diam. Praesent fermentum odio non aliquet euismod. Quisque commodo et lectus nec maximus. ",
      "slug": "product-73",
      "brand": "armaani",
      "rating": 4
    },
    {
      "id": 1074,
      "category": "Category 3",
      "name": "Product 74",
      "image": "https://picsum.photos/400?image=934",
      "stock": true,
      "price": "3360.129",
      "description": " Integer suscipit sapien magna, vitae hendrerit eros luctus ut. Quisque id suscipit augue, rutrum faucibus tortor. Proin ac tortor orci. Nullam erat justo, bibendum at ultricies sed, mollis ut nunc. Nunc leo nunc, placerat ac elementum vel, luctus eget lacus. Nunc ultrices pulvinar nulla, eu viverra ligula aliquet vel. In ullamcorper risus risus, non efficitur nunc eleifend vitae. Nulla rutrum placerat nibh a laoreet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque in felis in risus ultricies tempor. Maecenas sit amet ornare diam. Praesent fermentum odio non aliquet euismod. Quisque commodo et lectus nec maximus. ",
      "slug": "product-74",
      "brand": "armaani",
      "rating": 3
    },
    {
      "id": 1075,
      "category": "Category 4",
      "name": "Product 75",
      "image": "https://picsum.photos/400?image=445",
      "stock": false,
      "price": "1961.797",
      "description": " Integer suscipit sapien magna, vitae hendrerit eros luctus ut. Quisque id suscipit augue, rutrum faucibus tortor. Proin ac tortor orci. Nullam erat justo, bibendum at ultricies sed, mollis ut nunc. Nunc leo nunc, placerat ac elementum vel, luctus eget lacus. Nunc ultrices pulvinar nulla, eu viverra ligula aliquet vel. In ullamcorper risus risus, non efficitur nunc eleifend vitae. Nulla rutrum placerat nibh a laoreet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque in felis in risus ultricies tempor. Maecenas sit amet ornare diam. Praesent fermentum odio non aliquet euismod. Quisque commodo et lectus nec maximus. ",
      "slug": "product-75",
      "brand": "armaani",
      "rating": 4
    },
    {
      "id": 1076,
      "category": "Category 3",
      "name": "Product 76",
      "image": "https://picsum.photos/400?image=784",
      "stock": false,
      "price": "3411.149",
      "description": " Integer suscipit sapien magna, vitae hendrerit eros luctus ut. Quisque id suscipit augue, rutrum faucibus tortor. Proin ac tortor orci. Nullam erat justo, bibendum at ultricies sed, mollis ut nunc. Nunc leo nunc, placerat ac elementum vel, luctus eget lacus. Nunc ultrices pulvinar nulla, eu viverra ligula aliquet vel. In ullamcorper risus risus, non efficitur nunc eleifend vitae. Nulla rutrum placerat nibh a laoreet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque in felis in risus ultricies tempor. Maecenas sit amet ornare diam. Praesent fermentum odio non aliquet euismod. Quisque commodo et lectus nec maximus. ",
      "slug": "product-76",
      "brand": "armaani",
      "rating": 3
    },
    {
      "id": 1077,
      "category": "Category 3",
      "name": "Product 77",
      "image": "https://picsum.photos/400?image=749",
      "stock": true,
      "price": "2987.495",
      "description": " Integer suscipit sapien magna, vitae hendrerit eros luctus ut. Quisque id suscipit augue, rutrum faucibus tortor. Proin ac tortor orci. Nullam erat justo, bibendum at ultricies sed, mollis ut nunc. Nunc leo nunc, placerat ac elementum vel, luctus eget lacus. Nunc ultrices pulvinar nulla, eu viverra ligula aliquet vel. In ullamcorper risus risus, non efficitur nunc eleifend vitae. Nulla rutrum placerat nibh a laoreet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque in felis in risus ultricies tempor. Maecenas sit amet ornare diam. Praesent fermentum odio non aliquet euismod. Quisque commodo et lectus nec maximus. ",
      "slug": "product-77",
      "brand": "armaani",
      "rating": 3
    },
    {
      "id": 1078,
      "category": "Category 4",
      "name": "Product 78",
      "image": "https://picsum.photos/400?image=170",
      "stock": false,
      "price": "3826.539",
      "description": " Integer suscipit sapien magna, vitae hendrerit eros luctus ut. Quisque id suscipit augue, rutrum faucibus tortor. Proin ac tortor orci. Nullam erat justo, bibendum at ultricies sed, mollis ut nunc. Nunc leo nunc, placerat ac elementum vel, luctus eget lacus. Nunc ultrices pulvinar nulla, eu viverra ligula aliquet vel. In ullamcorper risus risus, non efficitur nunc eleifend vitae. Nulla rutrum placerat nibh a laoreet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque in felis in risus ultricies tempor. Maecenas sit amet ornare diam. Praesent fermentum odio non aliquet euismod. Quisque commodo et lectus nec maximus. ",
      "slug": "product-78",
      "brand": "armaani",
      "rating": 4
    },
    {
      "id": 1079,
      "category": "Category 3",
      "name": "Product 79",
      "image": "https://picsum.photos/400?image=405",
      "stock": true,
      "price": "1442.522",
      "description": " Integer suscipit sapien magna, vitae hendrerit eros luctus ut. Quisque id suscipit augue, rutrum faucibus tortor. Proin ac tortor orci. Nullam erat justo, bibendum at ultricies sed, mollis ut nunc. Nunc leo nunc, placerat ac elementum vel, luctus eget lacus. Nunc ultrices pulvinar nulla, eu viverra ligula aliquet vel. In ullamcorper risus risus, non efficitur nunc eleifend vitae. Nulla rutrum placerat nibh a laoreet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque in felis in risus ultricies tempor. Maecenas sit amet ornare diam. Praesent fermentum odio non aliquet euismod. Quisque commodo et lectus nec maximus. ",
      "slug": "product-79",
      "brand": "armaani",
      "rating": 4
    },
    {
      "id": 1080,
      "category": "Category 4",
      "name": "Product 80",
      "image": "https://picsum.photos/400?image=734",
      "stock": true,
      "price": "2897.202",
      "description": " Integer suscipit sapien magna, vitae hendrerit eros luctus ut. Quisque id suscipit augue, rutrum faucibus tortor. Proin ac tortor orci. Nullam erat justo, bibendum at ultricies sed, mollis ut nunc. Nunc leo nunc, placerat ac elementum vel, luctus eget lacus. Nunc ultrices pulvinar nulla, eu viverra ligula aliquet vel. In ullamcorper risus risus, non efficitur nunc eleifend vitae. Nulla rutrum placerat nibh a laoreet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque in felis in risus ultricies tempor. Maecenas sit amet ornare diam. Praesent fermentum odio non aliquet euismod. Quisque commodo et lectus nec maximus. ",
      "slug": "product-80",
      "brand": "armaani",
      "rating": 3
    },
    {
      "id": 1081,
      "category": "Category 1",
      "name": "Product 81",
      "image": "https://picsum.photos/400?image=615",
      "stock": false,
      "price": "1438.759",
      "description": " Integer suscipit sapien magna, vitae hendrerit eros luctus ut. Quisque id suscipit augue, rutrum faucibus tortor. Proin ac tortor orci. Nullam erat justo, bibendum at ultricies sed, mollis ut nunc. Nunc leo nunc, placerat ac elementum vel, luctus eget lacus. Nunc ultrices pulvinar nulla, eu viverra ligula aliquet vel. In ullamcorper risus risus, non efficitur nunc eleifend vitae. Nulla rutrum placerat nibh a laoreet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque in felis in risus ultricies tempor. Maecenas sit amet ornare diam. Praesent fermentum odio non aliquet euismod. Quisque commodo et lectus nec maximus. ",
      "slug": "product-81",
      "brand": "armaani",
      "rating": 3
    },
    {
      "id": 1082,
      "category": "Category 2",
      "name": "Product 82",
      "image": "https://picsum.photos/400?image=306",
      "stock": true,
      "price": "2811.252",
      "description": " Integer suscipit sapien magna, vitae hendrerit eros luctus ut. Quisque id suscipit augue, rutrum faucibus tortor. Proin ac tortor orci. Nullam erat justo, bibendum at ultricies sed, mollis ut nunc. Nunc leo nunc, placerat ac elementum vel, luctus eget lacus. Nunc ultrices pulvinar nulla, eu viverra ligula aliquet vel. In ullamcorper risus risus, non efficitur nunc eleifend vitae. Nulla rutrum placerat nibh a laoreet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque in felis in risus ultricies tempor. Maecenas sit amet ornare diam. Praesent fermentum odio non aliquet euismod. Quisque commodo et lectus nec maximus. ",
      "slug": "product-82",
      "brand": "armaani",
      "rating": 5
    },
    {
      "id": 1083,
      "category": "Category 1",
      "name": "Product 83",
      "image": "https://picsum.photos/400?image=306",
      "stock": false,
      "price": "1325.896",
      "description": " Integer suscipit sapien magna, vitae hendrerit eros luctus ut. Quisque id suscipit augue, rutrum faucibus tortor. Proin ac tortor orci. Nullam erat justo, bibendum at ultricies sed, mollis ut nunc. Nunc leo nunc, placerat ac elementum vel, luctus eget lacus. Nunc ultrices pulvinar nulla, eu viverra ligula aliquet vel. In ullamcorper risus risus, non efficitur nunc eleifend vitae. Nulla rutrum placerat nibh a laoreet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque in felis in risus ultricies tempor. Maecenas sit amet ornare diam. Praesent fermentum odio non aliquet euismod. Quisque commodo et lectus nec maximus. ",
      "slug": "product-83",
      "brand": "armaani",
      "rating": 4
    },
    {
      "id": 1084,
      "category": "Category 2",
      "name": "Product 84",
      "image": "https://picsum.photos/400?image=364",
      "stock": false,
      "price": "2783.140",
      "description": " Integer suscipit sapien magna, vitae hendrerit eros luctus ut. Quisque id suscipit augue, rutrum faucibus tortor. Proin ac tortor orci. Nullam erat justo, bibendum at ultricies sed, mollis ut nunc. Nunc leo nunc, placerat ac elementum vel, luctus eget lacus. Nunc ultrices pulvinar nulla, eu viverra ligula aliquet vel. In ullamcorper risus risus, non efficitur nunc eleifend vitae. Nulla rutrum placerat nibh a laoreet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque in felis in risus ultricies tempor. Maecenas sit amet ornare diam. Praesent fermentum odio non aliquet euismod. Quisque commodo et lectus nec maximus. ",
      "slug": "product-84",
      "brand": "armaani",
      "rating": 5
    },
    {
      "id": 1085,
      "category": "Category 3",
      "name": "Product 85",
      "image": "https://picsum.photos/400?image=251",
      "stock": true,
      "price": "1459.375",
      "description": " Integer suscipit sapien magna, vitae hendrerit eros luctus ut. Quisque id suscipit augue, rutrum faucibus tortor. Proin ac tortor orci. Nullam erat justo, bibendum at ultricies sed, mollis ut nunc. Nunc leo nunc, placerat ac elementum vel, luctus eget lacus. Nunc ultrices pulvinar nulla, eu viverra ligula aliquet vel. In ullamcorper risus risus, non efficitur nunc eleifend vitae. Nulla rutrum placerat nibh a laoreet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque in felis in risus ultricies tempor. Maecenas sit amet ornare diam. Praesent fermentum odio non aliquet euismod. Quisque commodo et lectus nec maximus. ",
      "slug": "product-85",
      "brand": "armaani",
      "rating": 3
    },
    {
      "id": 1086,
      "category": "Category 3",
      "name": "Product 86",
      "image": "https://picsum.photos/400?image=583",
      "stock": false,
      "price": "1788.136",
      "description": " Integer suscipit sapien magna, vitae hendrerit eros luctus ut. Quisque id suscipit augue, rutrum faucibus tortor. Proin ac tortor orci. Nullam erat justo, bibendum at ultricies sed, mollis ut nunc. Nunc leo nunc, placerat ac elementum vel, luctus eget lacus. Nunc ultrices pulvinar nulla, eu viverra ligula aliquet vel. In ullamcorper risus risus, non efficitur nunc eleifend vitae. Nulla rutrum placerat nibh a laoreet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque in felis in risus ultricies tempor. Maecenas sit amet ornare diam. Praesent fermentum odio non aliquet euismod. Quisque commodo et lectus nec maximus. ",
      "slug": "product-86",
      "brand": "armaani",
      "rating": 5
    },
    {
      "id": 1087,
      "category": "Category 4",
      "name": "Product 87",
      "image": "https://picsum.photos/400?image=909",
      "stock": false,
      "price": "1016.942",
      "description": " Integer suscipit sapien magna, vitae hendrerit eros luctus ut. Quisque id suscipit augue, rutrum faucibus tortor. Proin ac tortor orci. Nullam erat justo, bibendum at ultricies sed, mollis ut nunc. Nunc leo nunc, placerat ac elementum vel, luctus eget lacus. Nunc ultrices pulvinar nulla, eu viverra ligula aliquet vel. In ullamcorper risus risus, non efficitur nunc eleifend vitae. Nulla rutrum placerat nibh a laoreet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque in felis in risus ultricies tempor. Maecenas sit amet ornare diam. Praesent fermentum odio non aliquet euismod. Quisque commodo et lectus nec maximus. ",
      "slug": "product-87",
      "brand": "armaani",
      "rating": 3
    },
    {
      "id": 1088,
      "category": "Category 1",
      "name": "Product 88",
      "image": "https://picsum.photos/400?image=178",
      "stock": true,
      "price": "1197.111",
      "description": " Integer suscipit sapien magna, vitae hendrerit eros luctus ut. Quisque id suscipit augue, rutrum faucibus tortor. Proin ac tortor orci. Nullam erat justo, bibendum at ultricies sed, mollis ut nunc. Nunc leo nunc, placerat ac elementum vel, luctus eget lacus. Nunc ultrices pulvinar nulla, eu viverra ligula aliquet vel. In ullamcorper risus risus, non efficitur nunc eleifend vitae. Nulla rutrum placerat nibh a laoreet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque in felis in risus ultricies tempor. Maecenas sit amet ornare diam. Praesent fermentum odio non aliquet euismod. Quisque commodo et lectus nec maximus. ",
      "slug": "product-88",
      "brand": "armaani",
      "rating": 3
    },
    {
      "id": 1089,
      "category": "Category 1",
      "name": "Product 89",
      "image": "https://picsum.photos/400?image=35",
      "stock": true,
      "price": "2431.142",
      "description": " Integer suscipit sapien magna, vitae hendrerit eros luctus ut. Quisque id suscipit augue, rutrum faucibus tortor. Proin ac tortor orci. Nullam erat justo, bibendum at ultricies sed, mollis ut nunc. Nunc leo nunc, placerat ac elementum vel, luctus eget lacus. Nunc ultrices pulvinar nulla, eu viverra ligula aliquet vel. In ullamcorper risus risus, non efficitur nunc eleifend vitae. Nulla rutrum placerat nibh a laoreet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque in felis in risus ultricies tempor. Maecenas sit amet ornare diam. Praesent fermentum odio non aliquet euismod. Quisque commodo et lectus nec maximus. ",
      "slug": "product-89",
      "brand": "armaani",
      "rating": 5
    },
    {
      "id": 1090,
      "category": "Category 4",
      "name": "Product 90",
      "image": "https://picsum.photos/400?image=270",
      "stock": true,
      "price": "3017.940",
      "description": " Integer suscipit sapien magna, vitae hendrerit eros luctus ut. Quisque id suscipit augue, rutrum faucibus tortor. Proin ac tortor orci. Nullam erat justo, bibendum at ultricies sed, mollis ut nunc. Nunc leo nunc, placerat ac elementum vel, luctus eget lacus. Nunc ultrices pulvinar nulla, eu viverra ligula aliquet vel. In ullamcorper risus risus, non efficitur nunc eleifend vitae. Nulla rutrum placerat nibh a laoreet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque in felis in risus ultricies tempor. Maecenas sit amet ornare diam. Praesent fermentum odio non aliquet euismod. Quisque commodo et lectus nec maximus. ",
      "slug": "product-90",
      "brand": "armaani",
      "rating": 3
    },
    {
      "id": 1091,
      "category": "Category 4",
      "name": "Product 91",
      "image": "https://picsum.photos/400?image=659",
      "stock": false,
      "price": "2561.082",
      "description": " Integer suscipit sapien magna, vitae hendrerit eros luctus ut. Quisque id suscipit augue, rutrum faucibus tortor. Proin ac tortor orci. Nullam erat justo, bibendum at ultricies sed, mollis ut nunc. Nunc leo nunc, placerat ac elementum vel, luctus eget lacus. Nunc ultrices pulvinar nulla, eu viverra ligula aliquet vel. In ullamcorper risus risus, non efficitur nunc eleifend vitae. Nulla rutrum placerat nibh a laoreet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque in felis in risus ultricies tempor. Maecenas sit amet ornare diam. Praesent fermentum odio non aliquet euismod. Quisque commodo et lectus nec maximus. ",
      "slug": "product-91",
      "brand": "armaani",
      "rating": 4
    },
    {
      "id": 1092,
      "category": "Category 1",
      "name": "Product 92",
      "image": "https://picsum.photos/400?image=87",
      "stock": false,
      "price": "3923.386",
      "description": " Integer suscipit sapien magna, vitae hendrerit eros luctus ut. Quisque id suscipit augue, rutrum faucibus tortor. Proin ac tortor orci. Nullam erat justo, bibendum at ultricies sed, mollis ut nunc. Nunc leo nunc, placerat ac elementum vel, luctus eget lacus. Nunc ultrices pulvinar nulla, eu viverra ligula aliquet vel. In ullamcorper risus risus, non efficitur nunc eleifend vitae. Nulla rutrum placerat nibh a laoreet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque in felis in risus ultricies tempor. Maecenas sit amet ornare diam. Praesent fermentum odio non aliquet euismod. Quisque commodo et lectus nec maximus. ",
      "slug": "product-92",
      "brand": "armaani",
      "rating": 3
    },
    {
      "id": 1093,
      "category": "Category 4",
      "name": "Product 93",
      "image": "https://picsum.photos/400?image=950",
      "stock": false,
      "price": "3589.372",
      "description": " Integer suscipit sapien magna, vitae hendrerit eros luctus ut. Quisque id suscipit augue, rutrum faucibus tortor. Proin ac tortor orci. Nullam erat justo, bibendum at ultricies sed, mollis ut nunc. Nunc leo nunc, placerat ac elementum vel, luctus eget lacus. Nunc ultrices pulvinar nulla, eu viverra ligula aliquet vel. In ullamcorper risus risus, non efficitur nunc eleifend vitae. Nulla rutrum placerat nibh a laoreet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque in felis in risus ultricies tempor. Maecenas sit amet ornare diam. Praesent fermentum odio non aliquet euismod. Quisque commodo et lectus nec maximus. ",
      "slug": "product-93",
      "brand": "armaani",
      "rating": 3
    },
    {
      "id": 1094,
      "category": "Category 3",
      "name": "Product 94",
      "image": "https://picsum.photos/400?image=468",
      "stock": true,
      "price": "2672.681",
      "description": " Integer suscipit sapien magna, vitae hendrerit eros luctus ut. Quisque id suscipit augue, rutrum faucibus tortor. Proin ac tortor orci. Nullam erat justo, bibendum at ultricies sed, mollis ut nunc. Nunc leo nunc, placerat ac elementum vel, luctus eget lacus. Nunc ultrices pulvinar nulla, eu viverra ligula aliquet vel. In ullamcorper risus risus, non efficitur nunc eleifend vitae. Nulla rutrum placerat nibh a laoreet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque in felis in risus ultricies tempor. Maecenas sit amet ornare diam. Praesent fermentum odio non aliquet euismod. Quisque commodo et lectus nec maximus. ",
      "slug": "product-94",
      "brand": "armaani",
      "rating": 3
    },
    {
      "id": 1095,
      "category": "Category 3",
      "name": "Product 95",
      "image": "https://picsum.photos/400?image=206",
      "stock": false,
      "price": "2422.757",
      "description": " Integer suscipit sapien magna, vitae hendrerit eros luctus ut. Quisque id suscipit augue, rutrum faucibus tortor. Proin ac tortor orci. Nullam erat justo, bibendum at ultricies sed, mollis ut nunc. Nunc leo nunc, placerat ac elementum vel, luctus eget lacus. Nunc ultrices pulvinar nulla, eu viverra ligula aliquet vel. In ullamcorper risus risus, non efficitur nunc eleifend vitae. Nulla rutrum placerat nibh a laoreet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque in felis in risus ultricies tempor. Maecenas sit amet ornare diam. Praesent fermentum odio non aliquet euismod. Quisque commodo et lectus nec maximus. ",
      "slug": "product-95",
      "brand": "armaani",
      "rating": 5
    },
    {
      "id": 1096,
      "category": "Category 4",
      "name": "Product 96",
      "image": "https://picsum.photos/400?image=670",
      "stock": true,
      "price": "1343.414",
      "description": " Integer suscipit sapien magna, vitae hendrerit eros luctus ut. Quisque id suscipit augue, rutrum faucibus tortor. Proin ac tortor orci. Nullam erat justo, bibendum at ultricies sed, mollis ut nunc. Nunc leo nunc, placerat ac elementum vel, luctus eget lacus. Nunc ultrices pulvinar nulla, eu viverra ligula aliquet vel. In ullamcorper risus risus, non efficitur nunc eleifend vitae. Nulla rutrum placerat nibh a laoreet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque in felis in risus ultricies tempor. Maecenas sit amet ornare diam. Praesent fermentum odio non aliquet euismod. Quisque commodo et lectus nec maximus. ",
      "slug": "product-96",
      "brand": "armaani",
      "rating": 4
    },
    {
      "id": 1097,
      "category": "Category 3",
      "name": "Product 97",
      "image": "https://picsum.photos/400?image=597",
      "stock": false,
      "price": "2634.721",
      "description": " Integer suscipit sapien magna, vitae hendrerit eros luctus ut. Quisque id suscipit augue, rutrum faucibus tortor. Proin ac tortor orci. Nullam erat justo, bibendum at ultricies sed, mollis ut nunc. Nunc leo nunc, placerat ac elementum vel, luctus eget lacus. Nunc ultrices pulvinar nulla, eu viverra ligula aliquet vel. In ullamcorper risus risus, non efficitur nunc eleifend vitae. Nulla rutrum placerat nibh a laoreet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque in felis in risus ultricies tempor. Maecenas sit amet ornare diam. Praesent fermentum odio non aliquet euismod. Quisque commodo et lectus nec maximus. ",
      "slug": "product-97",
      "brand": "armaani",
      "rating": 3
    },
    {
      "id": 1098,
      "category": "Category 3",
      "name": "Product 98",
      "image": "https://picsum.photos/400?image=493",
      "stock": true,
      "price": "2864.759",
      "description": " Integer suscipit sapien magna, vitae hendrerit eros luctus ut. Quisque id suscipit augue, rutrum faucibus tortor. Proin ac tortor orci. Nullam erat justo, bibendum at ultricies sed, mollis ut nunc. Nunc leo nunc, placerat ac elementum vel, luctus eget lacus. Nunc ultrices pulvinar nulla, eu viverra ligula aliquet vel. In ullamcorper risus risus, non efficitur nunc eleifend vitae. Nulla rutrum placerat nibh a laoreet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque in felis in risus ultricies tempor. Maecenas sit amet ornare diam. Praesent fermentum odio non aliquet euismod. Quisque commodo et lectus nec maximus. ",
      "slug": "product-98",
      "brand": "armaani",
      "rating": 3
    },
    {
      "id": 1099,
      "category": "Category 2",
      "name": "Product 99",
      "image": "https://picsum.photos/400?image=195",
      "stock": true,
      "price": "3325.989",
      "description": " Integer suscipit sapien magna, vitae hendrerit eros luctus ut. Quisque id suscipit augue, rutrum faucibus tortor. Proin ac tortor orci. Nullam erat justo, bibendum at ultricies sed, mollis ut nunc. Nunc leo nunc, placerat ac elementum vel, luctus eget lacus. Nunc ultrices pulvinar nulla, eu viverra ligula aliquet vel. In ullamcorper risus risus, non efficitur nunc eleifend vitae. Nulla rutrum placerat nibh a laoreet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque in felis in risus ultricies tempor. Maecenas sit amet ornare diam. Praesent fermentum odio non aliquet euismod. Quisque commodo et lectus nec maximus. ",
      "slug": "product-99",
      "brand": "armaani",
      "rating": 4
    },
    {
      "id": 1100,
      "category": "Category 4",
      "name": "Product 100",
      "image": "https://picsum.photos/400?image=828",
      "stock": true,
      "price": "2120.988",
      "description": " Integer suscipit sapien magna, vitae hendrerit eros luctus ut. Quisque id suscipit augue, rutrum faucibus tortor. Proin ac tortor orci. Nullam erat justo, bibendum at ultricies sed, mollis ut nunc. Nunc leo nunc, placerat ac elementum vel, luctus eget lacus. Nunc ultrices pulvinar nulla, eu viverra ligula aliquet vel. In ullamcorper risus risus, non efficitur nunc eleifend vitae. Nulla rutrum placerat nibh a laoreet. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Pellentesque in felis in risus ultricies tempor. Maecenas sit amet ornare diam. Praesent fermentum odio non aliquet euismod. Quisque commodo et lectus nec maximus. ",
      "slug": "product-100",
      "brand": "armaani",
      "rating": 5
    }
  ]
}

export default data;